apiVersion: v1
kind: Service
metadata:
  name: verse-train
  namespace: default
spec:
  selector:
    app: res
  type: NodePort
  ports:
  - name: ssh
    protocol: TCP
    port: 22
    targetPort: 22
    # If you set the `spec.type` field to `NodePort` and you want a specific port number,
    # you can specify a value in the `spec.ports[*].nodePort` field.
    nodePort: 32444
  - name: tensorboard
    protocol: TCP
    port: 6006
    targetPort: 6006
    nodePort: 32006
